/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MenuPreviewRouteImport } from './routes/menu-preview'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/_dashboard/route'
import { Route as EmailVerifiedIndexRouteImport } from './routes/email-verified/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as AuthStudioProjectIdRouteRouteImport } from './routes/_auth/studio/$projectId/route'
import { Route as ApiAssetsIndexRouteImport } from './routes/api/assets/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthDashboardBillingIndexRouteImport } from './routes/_auth/_dashboard/billing/index'
import { Route as AuthDashboardProjectsIndexRouteImport } from './routes/_auth/_dashboard/projects/index'
import { Route as AuthBillingCheckoutSessionIdRouteImport } from './routes/_auth/billing/checkout.$sessionId'
import { Route as AuthBillingTopupSessionIdRouteImport } from './routes/_auth/billing/topup.$sessionId'
import { Route as AuthStudioProjectIdIndexRouteImport } from './routes/_auth/studio/$projectId/index'
import { Route as ApiAssetsAssetIdCompleteRouteImport } from './routes/api/assets/$assetId/complete'
import { Route as ApiAssetsAssetIdContentRouteImport } from './routes/api/assets/$assetId/content'
import { Route as ApiAssetsAssetIdContentFilenameRouteImport } from './routes/api/assets/$assetId/content.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuPreviewRoute = MenuPreviewRouteImport.update({
  id: '/menu-preview',
  path: '/menu-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const EmailVerifiedIndexRoute = EmailVerifiedIndexRouteImport.update({
  id: '/email-verified/',
  path: '/email-verified/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStudioProjectIdRouteRoute =
  AuthStudioProjectIdRouteRouteImport.update({
    id: '/studio/$projectId',
    path: '/studio/$projectId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const ApiAssetsIndexRoute = ApiAssetsIndexRouteImport.update({
  id: '/api/assets/',
  path: '/api/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardBillingIndexRoute =
  AuthDashboardBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthDashboardProjectsIndexRoute =
  AuthDashboardProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthDashboardRouteRoute,
  } as any)
const AuthBillingCheckoutSessionIdRoute =
  AuthBillingCheckoutSessionIdRouteImport.update({
    id: '/billing/checkout/$sessionId',
    path: '/billing/checkout/$sessionId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthBillingTopupSessionIdRoute =
  AuthBillingTopupSessionIdRouteImport.update({
    id: '/billing/topup/$sessionId',
    path: '/billing/topup/$sessionId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthStudioProjectIdIndexRoute =
  AuthStudioProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthStudioProjectIdRouteRoute,
  } as any)
const ApiAssetsAssetIdCompleteRoute =
  ApiAssetsAssetIdCompleteRouteImport.update({
    id: '/api/assets/$assetId/complete',
    path: '/api/assets/$assetId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAssetsAssetIdContentRoute = ApiAssetsAssetIdContentRouteImport.update({
  id: '/api/assets/$assetId/content',
  path: '/api/assets/$assetId/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsAssetIdContentFilenameRoute =
  ApiAssetsAssetIdContentFilenameRouteImport.update({
    id: '/$filename',
    path: '/$filename',
    getParentRoute: () => ApiAssetsAssetIdContentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/menu-preview': typeof MenuPreviewRoute
  '/email-verified/': typeof EmailVerifiedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/studio/$projectId': typeof AuthStudioProjectIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/assets/': typeof ApiAssetsIndexRoute
  '/billing/checkout/$sessionId': typeof AuthBillingCheckoutSessionIdRoute
  '/billing/topup/$sessionId': typeof AuthBillingTopupSessionIdRoute
  '/api/assets/$assetId/complete': typeof ApiAssetsAssetIdCompleteRoute
  '/api/assets/$assetId/content': typeof ApiAssetsAssetIdContentRouteWithChildren
  '/billing/': typeof AuthDashboardBillingIndexRoute
  '/projects/': typeof AuthDashboardProjectsIndexRoute
  '/studio/$projectId/': typeof AuthStudioProjectIdIndexRoute
  '/api/assets/$assetId/content/$filename': typeof ApiAssetsAssetIdContentFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/menu-preview': typeof MenuPreviewRoute
  '/email-verified': typeof EmailVerifiedIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/assets': typeof ApiAssetsIndexRoute
  '/billing/checkout/$sessionId': typeof AuthBillingCheckoutSessionIdRoute
  '/billing/topup/$sessionId': typeof AuthBillingTopupSessionIdRoute
  '/api/assets/$assetId/complete': typeof ApiAssetsAssetIdCompleteRoute
  '/api/assets/$assetId/content': typeof ApiAssetsAssetIdContentRouteWithChildren
  '/billing': typeof AuthDashboardBillingIndexRoute
  '/projects': typeof AuthDashboardProjectsIndexRoute
  '/studio/$projectId': typeof AuthStudioProjectIdIndexRoute
  '/api/assets/$assetId/content/$filename': typeof ApiAssetsAssetIdContentFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/menu-preview': typeof MenuPreviewRoute
  '/_auth/_dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/email-verified/': typeof EmailVerifiedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/_auth/studio/$projectId': typeof AuthStudioProjectIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/assets/': typeof ApiAssetsIndexRoute
  '/_auth/billing/checkout/$sessionId': typeof AuthBillingCheckoutSessionIdRoute
  '/_auth/billing/topup/$sessionId': typeof AuthBillingTopupSessionIdRoute
  '/api/assets/$assetId/complete': typeof ApiAssetsAssetIdCompleteRoute
  '/api/assets/$assetId/content': typeof ApiAssetsAssetIdContentRouteWithChildren
  '/_auth/_dashboard/billing/': typeof AuthDashboardBillingIndexRoute
  '/_auth/_dashboard/projects/': typeof AuthDashboardProjectsIndexRoute
  '/_auth/studio/$projectId/': typeof AuthStudioProjectIdIndexRoute
  '/api/assets/$assetId/content/$filename': typeof ApiAssetsAssetIdContentFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/menu-preview'
    | '/email-verified/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/signup/'
    | '/studio/$projectId'
    | '/api/auth/$'
    | '/api/assets/'
    | '/billing/checkout/$sessionId'
    | '/billing/topup/$sessionId'
    | '/api/assets/$assetId/complete'
    | '/api/assets/$assetId/content'
    | '/billing/'
    | '/projects/'
    | '/studio/$projectId/'
    | '/api/assets/$assetId/content/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/menu-preview'
    | '/email-verified'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/auth/$'
    | '/api/assets'
    | '/billing/checkout/$sessionId'
    | '/billing/topup/$sessionId'
    | '/api/assets/$assetId/complete'
    | '/api/assets/$assetId/content'
    | '/billing'
    | '/projects'
    | '/studio/$projectId'
    | '/api/assets/$assetId/content/$filename'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/menu-preview'
    | '/_auth/_dashboard'
    | '/email-verified/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/signup/'
    | '/_auth/studio/$projectId'
    | '/api/auth/$'
    | '/api/assets/'
    | '/_auth/billing/checkout/$sessionId'
    | '/_auth/billing/topup/$sessionId'
    | '/api/assets/$assetId/complete'
    | '/api/assets/$assetId/content'
    | '/_auth/_dashboard/billing/'
    | '/_auth/_dashboard/projects/'
    | '/_auth/studio/$projectId/'
    | '/api/assets/$assetId/content/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MenuPreviewRoute: typeof MenuPreviewRoute
  EmailVerifiedIndexRoute: typeof EmailVerifiedIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAssetsIndexRoute: typeof ApiAssetsIndexRoute
  ApiAssetsAssetIdCompleteRoute: typeof ApiAssetsAssetIdCompleteRoute
  ApiAssetsAssetIdContentRoute: typeof ApiAssetsAssetIdContentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-preview': {
      id: '/menu-preview'
      path: '/menu-preview'
      fullPath: '/menu-preview'
      preLoaderRoute: typeof MenuPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_dashboard': {
      id: '/_auth/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/email-verified/': {
      id: '/email-verified/'
      path: '/email-verified'
      fullPath: '/email-verified/'
      preLoaderRoute: typeof EmailVerifiedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/studio/$projectId': {
      id: '/_auth/studio/$projectId'
      path: '/studio/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof AuthStudioProjectIdRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/assets/': {
      id: '/api/assets/'
      path: '/api/assets'
      fullPath: '/api/assets/'
      preLoaderRoute: typeof ApiAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_dashboard/billing/': {
      id: '/_auth/_dashboard/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthDashboardBillingIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/_dashboard/projects/': {
      id: '/_auth/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthDashboardProjectsIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/billing/checkout/$sessionId': {
      id: '/_auth/billing/checkout/$sessionId'
      path: '/billing/checkout/$sessionId'
      fullPath: '/billing/checkout/$sessionId'
      preLoaderRoute: typeof AuthBillingCheckoutSessionIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/billing/topup/$sessionId': {
      id: '/_auth/billing/topup/$sessionId'
      path: '/billing/topup/$sessionId'
      fullPath: '/billing/topup/$sessionId'
      preLoaderRoute: typeof AuthBillingTopupSessionIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/studio/$projectId/': {
      id: '/_auth/studio/$projectId/'
      path: '/'
      fullPath: '/studio/$projectId/'
      preLoaderRoute: typeof AuthStudioProjectIdIndexRouteImport
      parentRoute: typeof AuthStudioProjectIdRouteRoute
    }
    '/api/assets/$assetId/complete': {
      id: '/api/assets/$assetId/complete'
      path: '/api/assets/$assetId/complete'
      fullPath: '/api/assets/$assetId/complete'
      preLoaderRoute: typeof ApiAssetsAssetIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$assetId/content': {
      id: '/api/assets/$assetId/content'
      path: '/api/assets/$assetId/content'
      fullPath: '/api/assets/$assetId/content'
      preLoaderRoute: typeof ApiAssetsAssetIdContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$assetId/content/$filename': {
      id: '/api/assets/$assetId/content/$filename'
      path: '/$filename'
      fullPath: '/api/assets/$assetId/content/$filename'
      preLoaderRoute: typeof ApiAssetsAssetIdContentFilenameRouteImport
      parentRoute: typeof ApiAssetsAssetIdContentRoute
    }
  }
}

interface AuthDashboardRouteRouteChildren {
  AuthDashboardBillingIndexRoute: typeof AuthDashboardBillingIndexRoute
  AuthDashboardProjectsIndexRoute: typeof AuthDashboardProjectsIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardBillingIndexRoute: AuthDashboardBillingIndexRoute,
  AuthDashboardProjectsIndexRoute: AuthDashboardProjectsIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthStudioProjectIdRouteRouteChildren {
  AuthStudioProjectIdIndexRoute: typeof AuthStudioProjectIdIndexRoute
}

const AuthStudioProjectIdRouteRouteChildren: AuthStudioProjectIdRouteRouteChildren =
  {
    AuthStudioProjectIdIndexRoute: AuthStudioProjectIdIndexRoute,
  }

const AuthStudioProjectIdRouteRouteWithChildren =
  AuthStudioProjectIdRouteRoute._addFileChildren(
    AuthStudioProjectIdRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
  AuthStudioProjectIdRouteRoute: typeof AuthStudioProjectIdRouteRouteWithChildren
  AuthBillingCheckoutSessionIdRoute: typeof AuthBillingCheckoutSessionIdRoute
  AuthBillingTopupSessionIdRoute: typeof AuthBillingTopupSessionIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
  AuthStudioProjectIdRouteRoute: AuthStudioProjectIdRouteRouteWithChildren,
  AuthBillingCheckoutSessionIdRoute: AuthBillingCheckoutSessionIdRoute,
  AuthBillingTopupSessionIdRoute: AuthBillingTopupSessionIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiAssetsAssetIdContentRouteChildren {
  ApiAssetsAssetIdContentFilenameRoute: typeof ApiAssetsAssetIdContentFilenameRoute
}

const ApiAssetsAssetIdContentRouteChildren: ApiAssetsAssetIdContentRouteChildren =
  {
    ApiAssetsAssetIdContentFilenameRoute: ApiAssetsAssetIdContentFilenameRoute,
  }

const ApiAssetsAssetIdContentRouteWithChildren =
  ApiAssetsAssetIdContentRoute._addFileChildren(
    ApiAssetsAssetIdContentRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MenuPreviewRoute: MenuPreviewRoute,
  EmailVerifiedIndexRoute: EmailVerifiedIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAssetsIndexRoute: ApiAssetsIndexRoute,
  ApiAssetsAssetIdCompleteRoute: ApiAssetsAssetIdCompleteRoute,
  ApiAssetsAssetIdContentRoute: ApiAssetsAssetIdContentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
